name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: remove, build and run docker
      run: |
        docker stop trackms || true && docker rm trackms || true
        docker build . --file Dockerfile --tag trackms
        docker run --name trackms -p 9030:80 trackms
